---
- name: "Set up a Matrix server"
  hosts: "{{ target if target is defined else 'matrix_servers' }}"
  become: true

  roles:
    # Most of the roles below are not distributed with the playbook, but downloaded separately using `ansible-galaxy` via the `make roles` command (see `Makefile`).
    - role: roles/galaxy/com.devture.ansible.role.playbook_help

    - role: roles/galaxy/com.devture.ansible.role.systemd_docker_base

    - role: roles/custom/matrix_playbook_migration

    - when: devture_timesync_installation_enabled | bool
      role: roles/galaxy/com.devture.ansible.role.timesync
      tags:
        - setup-timesync
        - setup-all

    - roles/custom/matrix-base
    - roles/custom/matrix-dynamic-dns
    - roles/custom/matrix-mailer
    - roles/custom/matrix-postgres
    - roles/custom/matrix-redis
    - roles/custom/matrix-corporal
    - roles/custom/matrix-bridge-appservice-discord
    - roles/custom/matrix-bridge-appservice-slack
    - roles/custom/matrix-bridge-appservice-webhooks
    - roles/custom/matrix-bridge-appservice-irc
    - roles/custom/matrix-bridge-appservice-kakaotalk
    - roles/custom/matrix-bridge-beeper-linkedin
    - roles/custom/matrix-bridge-go-skype-bridge
    - roles/custom/matrix-bridge-mautrix-facebook
    - roles/custom/matrix-bridge-mautrix-twitter
    - roles/custom/matrix-bridge-mautrix-hangouts
    - roles/custom/matrix-bridge-mautrix-googlechat
    - roles/custom/matrix-bridge-mautrix-instagram
    - roles/custom/matrix-bridge-mautrix-signal
    - roles/custom/matrix-bridge-mautrix-telegram
    - roles/custom/matrix-bridge-mautrix-whatsapp
    - roles/custom/matrix-bridge-mautrix-discord
    - roles/custom/matrix-bridge-mx-puppet-discord
    - roles/custom/matrix-bridge-mx-puppet-groupme
    - roles/custom/matrix-bridge-mx-puppet-steam
    - roles/custom/matrix-bridge-mx-puppet-slack
    - roles/custom/matrix-bridge-mx-puppet-twitter
    - roles/custom/matrix-bridge-mx-puppet-instagram
    - roles/custom/matrix-bridge-sms
    - roles/custom/matrix-bridge-heisenbridge
    - roles/custom/matrix-bridge-hookshot
    - roles/custom/matrix-bot-matrix-reminder-bot
    - roles/custom/matrix-bot-matrix-registration-bot
    - roles/custom/matrix-bot-maubot
    - roles/custom/matrix-bot-buscarron
    - roles/custom/matrix-bot-honoroit
    - roles/custom/matrix-bot-postmoogle
    - roles/custom/matrix-bot-go-neb
    - roles/custom/matrix-bot-mjolnir
    - roles/custom/matrix-cactus-comments
    - roles/custom/matrix-synapse
    - roles/custom/matrix-dendrite
    - roles/custom/matrix-conduit
    - roles/custom/matrix-synapse-admin
    - roles/custom/matrix-prometheus-node-exporter
    - roles/custom/matrix-prometheus-postgres-exporter
    - roles/custom/matrix-prometheus
    - roles/custom/matrix-grafana
    - roles/custom/matrix-registration
    - roles/custom/matrix-client-element
    - roles/custom/matrix-client-hydrogen
    - roles/custom/matrix-client-cinny
    - roles/custom/matrix-jitsi
    - roles/custom/matrix-ldap-registration-proxy
    - roles/custom/matrix-ma1sd
    - roles/custom/matrix-dimension
    - roles/custom/matrix-etherpad
    - roles/custom/matrix-email2matrix
    - roles/custom/matrix-sygnal
    - roles/custom/matrix-ntfy
    - roles/custom/matrix-nginx-proxy
    - roles/custom/matrix-coturn
    - roles/custom/matrix-aux
    - roles/custom/matrix-postgres-backup
    - roles/custom/matrix-backup-borg
    - roles/custom/matrix-user-creator
    - roles/custom/matrix-common-after

    # This is pretty much last, because we want it to better serve as a "last known good configuration".
    # See: https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2217#issuecomment-1301487601
    - when: devture_playbook_state_preserver_enabled | bool
      role: roles/galaxy/com.devture.ansible.role.playbook_state_preserver
      tags:
        - setup-all

    - role: roles/galaxy/com.devture.ansible.role.playbook_runtime_messages
